name = "Monstera"
uuid = "a7c66a61-db7e-4bbc-973a-3292ef8425af"
authors = ["eascarrunz <eascarrunz.dev@mailfence.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
